import type { CreativeDirection, PlanningSource, Scene } from "@/types/content";

export const planningSources: PlanningSource[] = [
  { id: "dermora-core", name: "DERMORA Core Launch Deck", kind: "approved-source", detail: "US · v4.2 · approved 12 Aug 2026", status: "current" },
  { id: "dermora-claims", name: "DERMORA Claims Library", kind: "claims", detail: "US · 24 approved claims · current", status: "current" },
  { id: "dermora-brand", name: "DERMORA Brand Kit", kind: "brand", detail: "Logo, packshot, typography and fair balance", status: "current" },
  { id: "hcp-detail-aid", name: "Approved HCP Detail Aid", kind: "existing-asset", detail: "Existing asset · approved May 2026", status: "current" },
  { id: "dermora-india", name: "DERMORA India Dossier", kind: "approved-source", detail: "India · v3.1 · approved 02 Aug 2026", status: "current" },
  { id: "clearskin-paper", name: "CLEARSKIN study publication", kind: "reference", detail: "External reference · not promotional approval", status: "reference-only" },
];

export const creativeDirections: CreativeDirection[] = [
  {
    id: "science-forward",
    name: "Science, made visible",
    eyebrow: "Recommended",
    summary: "A precise clinical story that turns the mechanism and pivotal evidence into a clear visual journey.",
    rationale: "Best fit for dermatologists who want the science quickly and without promotional theatre.",
    palette: ["#183d32", "#d9ef62", "#f3f7f1"],
    structure: ["Unmet need", "Mechanism", "Pivotal evidence", "Role in care", "Close"],
    risk: "Low",
  },
  {
    id: "practice-first",
    name: "The clinical moment",
    eyebrow: "Practice-led",
    summary: "Begin inside the treatment decision, then reveal the product science as the answer to a familiar challenge.",
    rationale: "More human and situational, with a clear bridge from practice tension to clinical evidence.",
    palette: ["#433b34", "#f2c7a5", "#f8f4ef"],
    structure: ["Clinical tension", "Patient impact", "New possibility", "Evidence", "Action"],
    risk: "Moderate",
  },
  {
    id: "signal-story",
    name: "Follow the signal",
    eyebrow: "Distinctive",
    summary: "A confident visual metaphor follows one biological signal from disease pathway to treatment response.",
    rationale: "Memorable and ownable, while remaining grounded in the approved mechanism and evidence.",
    palette: ["#202c45", "#8fd8cc", "#f2f5f8"],
    structure: ["Signal", "Disruption", "Intervention", "Response", "Implication"],
    risk: "Moderate",
  },
];

export const scenes: Scene[] = [
  {
    id: "scene-1",
    avatar: { name: "Dr. Maya Chen · clinical and warm", role: "Consultant Dermatologist", position: "bottom-left", scale: 0.62 },
    backgroundKind: "video",
    bgVideoSrc: "/133898-758336558_medium.mp4",
    shots: [
      { id: "s1-a", index: 1, startAt: 0,   endAt: 3.2, label: "Establish the patient",   transitionIn: "Open on black", narrationFragment: 'For adults living with moderate-to-severe plaque psoriasis,', visualStory: 'Opens on a restrained clinical portrait; the headline fades up over a still frame before any motion begins.' },
      { id: "s1-b", index: 2, startAt: 3.2, endAt: 7.2, label: "Widen to the burden",     transitionIn: "Slow push in 4%", narrationFragment: 'visible symptoms can be only part of the burden.', visualStory: 'The camera pushes in slowly as the portrait gives way to an abstract skin-barrier landscape behind the copy.' },
      { id: "s1-c", index: 3, startAt: 7.2, endAt: 8.0, label: "Hold before the turn",    transitionIn: "Fade out 240ms", narrationFragment: '', visualStory: 'Copy clears and the frame holds empty for a beat, setting up the cut to mechanism.' },
    ],
    timings: [
      { elementId: "headline",  inAt: 0.4, outAt: 7.2, transitionIn: "Fade up 320ms", transitionOut: "Fade out 240ms" },
      { elementId: "narration", inAt: 0.8, outAt: 8.0, transitionIn: "Word-by-word reveal", transitionOut: "Hold to cut" },
      { elementId: "background", inAt: 0, outAt: 8.0, transitionIn: "Slow push in 4%", transitionOut: "Cross dissolve 400ms" },
      { elementId: "voiceover", inAt: 0.8, outAt: 8.0, transitionIn: "Fade in 200ms", transitionOut: "Fade out 400ms" },
      { elementId: "sfx", inAt: 0, outAt: 1.6, transitionIn: "Cut in", transitionOut: "Duck under VO" },
      { elementId: "avatar", inAt: 0.6, outAt: 7.2, transitionIn: "Fade up 320ms", transitionOut: "Fade out 240ms" },
      { elementId: "bg-video", inAt: 0, outAt: 8.0, transitionIn: "Fade up from black 600ms", transitionOut: "Cross dissolve 400ms" },
    ],
    number: 1,
    title: "The unresolved burden",
    duration: 8,
    narration: "For adults living with moderate-to-severe plaque psoriasis, visible symptoms can be only part of the burden.",
    visual: "A restrained clinical portrait gives way to an abstract skin-barrier landscape with dark emerald accents.",
    negativeVisual: "Overly stylized cartoons, text overlays, harsh shadows, low quality rendering.",
    claim: "Disease-burden statement",
    evidenceState: "supported",
    narrativeTag: "Intro",
    mediaType: "none",
  },
  {
    id: "scene-2",
    shots: [
      { id: "s2-a", index: 1, startAt: 0,   endAt: 2.0, label: "Name the target",        transitionIn: "Cut", narrationFragment: 'DERMORA binds selectively at the intended receptor,', visualStory: 'Title lands on a clean plate with no media behind it.' },
      { id: "s2-b", index: 2, startAt: 2.0, endAt: 4.5, label: "Bring in the pathway",   transitionIn: "Scale up 4% ease-out", narrationFragment: 'blocking the downstream signal', visualStory: 'The pathway clip scales up into frame behind the copy as the receptor is named.' },
      { id: "s2-c", index: 3, startAt: 4.5, endAt: 9.4, label: "Hold on the mechanism",  transitionIn: "Fade out 200ms", narrationFragment: 'that drives plaque formation.', visualStory: 'Title drops away and the clip carries the frame alone while the mechanism resolves.' },
      { id: "s2-d", index: 4, startAt: 9.4, endAt: 10.0, label: "Clear to outro",        transitionIn: "Cross dissolve 360ms", narrationFragment: '', visualStory: 'Clip dissolves out, clearing to the evidence scene.' },
    ],
    timings: [
      { elementId: "headline",   inAt: 0.3, outAt: 4.5, transitionIn: "Fade up 280ms", transitionOut: "Fade out 200ms" },
      { elementId: "narration",  inAt: 0.6, outAt: 10.0, transitionIn: "Word-by-word reveal", transitionOut: "Hold to cut" },
      { elementId: "video-clip", inAt: 2.0, outAt: 9.4, transitionIn: "Scale up 4% ease-out", transitionOut: "Cross dissolve 360ms" },
      { elementId: "background", inAt: 0, outAt: 10.0, transitionIn: "Cut", transitionOut: "Cross dissolve 400ms" },
      { elementId: "voiceover", inAt: 0.6, outAt: 10.0, transitionIn: "Fade in 200ms", transitionOut: "Fade out 400ms" },
      { elementId: "sfx", inAt: 2.0, outAt: 4.5, transitionIn: "Fade in 120ms", transitionOut: "Duck under VO" },
    ],
    number: 2,
    title: "A precise target",
    duration: 10,
    narration: "DERMORA binds selectively at the intended receptor, blocking the downstream signal that drives plaque formation.",
    visual: "A single lime signal travels through a minimal pathway model, isolating the therapeutic target.",
    negativeVisual: "Unscientific illustrations, generic cellular shapes, blurry receptor bindings.",
    claim: "Mechanism-of-action statement",
    evidenceState: "approved",
    narrativeTag: "Mechanism",
    mediaType: "video",
    mediaVideoSrc: "/reel-moa.mp4",
    mediaLabel: "3D Receptor MoA Kinematics",
  },
  {
    id: "scene-3",
    graph: {
      title: "PASI 90 response at Week 16",
      unit: "% of patients",
      max: 60,
      series: [
        { label: "DERMORA", value: 52, highlight: true },
        { label: "Active comparator", value: 34 },
        { label: "Placebo", value: 18 },
      ],
      footnote: "CLEARSKIN-3 · p < 0.001 vs placebo",
    },
    shots: [
      { id: "s3-a", index: 1, startAt: 0,    endAt: 1.2,  label: "Title on clean plate",   transitionIn: "Cut", narrationFragment: 'In the pivotal CLEARSKIN study,', visualStory: 'Title on a clean plate; no media yet, so the claim reads before anything moves.' },
      { id: "s3-b", index: 2, startAt: 1.2,  endAt: 5.0,  label: "Bring in the still",     transitionIn: "Cross dissolve 400ms", narrationFragment: 'a greater proportion of patients', visualStory: 'The anatomical still cross-dissolves in beside the copy as the population is described.' },
      { id: "s3-c", index: 3, startAt: 5.0,  endAt: 6.4,  label: "Drop the title",         transitionIn: "Fade out 200ms", narrationFragment: 'achieved the primary endpoint', visualStory: 'Title fades out, leaving the still to hold the frame through the endpoint line.' },
      { id: "s3-d", index: 4, startAt: 6.4,  endAt: 8.6,  label: "Wipe in the chart",      transitionIn: "Wipe from right 420ms", narrationFragment: 'at Week 16.', visualStory: 'The comparative chart wipes in from the right while the still is still on screen — both media overlap here.' },
      { id: "s3-e", index: 5, startAt: 8.6,  endAt: 14.0, label: "Chart carries the read", transitionIn: "Fade out 300ms", narrationFragment: '', visualStory: 'Still fades out and the chart carries the read-out alone to the end of the scene.' },
    ],
    timings: [
      { elementId: "headline",   inAt: 0.3, outAt: 5.0, transitionIn: "Fade up 280ms", transitionOut: "Fade out 200ms" },
      { elementId: "narration",  inAt: 0.7, outAt: 14.0, transitionIn: "Word-by-word reveal", transitionOut: "Hold to cut" },
      { elementId: "image",      inAt: 1.2, outAt: 8.6, transitionIn: "Cross dissolve 400ms", transitionOut: "Fade out 300ms" },
      { elementId: "video-clip", inAt: 6.4, outAt: 14.0, transitionIn: "Wipe from right 420ms", transitionOut: "Cross dissolve 360ms" },
      { elementId: "background", inAt: 0, outAt: 14.0, transitionIn: "Cut", transitionOut: "Cross dissolve 400ms" },
      { elementId: "voiceover", inAt: 0.7, outAt: 14.0, transitionIn: "Fade in 200ms", transitionOut: "Fade out 400ms" },
      { elementId: "sfx", inAt: 6.4, outAt: 8.6, transitionIn: "Cut in on wipe", transitionOut: "Duck under VO" },
      { elementId: "graph", inAt: 8.6, outAt: 14.0, transitionIn: "Bars draw up 900ms", transitionOut: "Fade out 300ms" },
    ],
    number: 3,
    title: "Pivotal evidence",
    duration: 14,
    narration: "In the pivotal CLEARSKIN study, a greater proportion of patients achieved the primary endpoint at Week 16.",
    visual: "Evidence resolves into a clean comparative chart with the primary endpoint highlighted in emerald glow.",
    negativeVisual: "Misleading axis scales, ungrounded statistical annotations, low contrast backgrounds.",
    claim: "CLEARSKIN primary endpoint",
    evidenceState: "approved",
    narrativeTag: "Evidence",
    mediaType: "both",
    mediaImageSrc: "/anatomical-heart.png",
    mediaVideoSrc: "/4360-178617258_medium.mp4",
    mediaLabel: "Cardiac & Vascular Model",
  },
  {
    id: "scene-4",
    shots: [
      { id: "s4-a", index: 1, startAt: 0,   endAt: 1.5,  label: "State the regimen",     transitionIn: "Cut", narrationFragment: 'One tablet daily,', visualStory: 'Regimen stated over a clean frame.' },
      { id: "s4-b", index: 2, startAt: 1.5, endAt: 4.2,  label: "Show the pack",         transitionIn: "Cross dissolve 400ms", narrationFragment: 'with no titration required,', visualStory: 'Packshot cross-dissolves in as the titration point is made.' },
      { id: "s4-c", index: 3, startAt: 4.2, endAt: 9.0,  label: "Hold on practice",      transitionIn: "Fade out 200ms", narrationFragment: 'supports a straightforward conversation about starting treatment.', visualStory: 'Title clears; the packshot holds while the practice line plays.' },
      { id: "s4-d", index: 4, startAt: 9.0, endAt: 10.0, label: "Clear the frame",       transitionIn: "Fade out 300ms", narrationFragment: '', visualStory: 'Packshot fades out, clearing the frame for the outro.' },
    ],
    timings: [
      { elementId: "headline",  inAt: 0.3, outAt: 4.2, transitionIn: "Fade up 280ms", transitionOut: "Fade out 200ms" },
      { elementId: "narration", inAt: 0.6, outAt: 10.0, transitionIn: "Word-by-word reveal", transitionOut: "Hold to cut" },
      { elementId: "image",     inAt: 1.5, outAt: 9.0, transitionIn: "Cross dissolve 400ms", transitionOut: "Fade out 300ms" },
      { elementId: "background", inAt: 0, outAt: 10.0, transitionIn: "Cut", transitionOut: "Fade to black 500ms" },
      { elementId: "voiceover", inAt: 0.6, outAt: 10.0, transitionIn: "Fade in 200ms", transitionOut: "Fade out 400ms" },
      { elementId: "sfx", inAt: 1.5, outAt: 3.0, transitionIn: "Fade in 120ms", transitionOut: "Duck under VO" },
    ],
    number: 4,
    title: "Designed for practice",
    duration: 10,
    narration: "One tablet daily, with no titration required, supports a straightforward conversation about starting treatment.",
    visual: "A simplified dosing sequence appears beside a calm physician–patient consultation vignette.",
    negativeVisual: "Cluttered dosage tables, promotional slogans, distracting non-clinical props.",
    claim: "Dosing statement",
    evidenceState: "changed",
    narrativeTag: "Dosing",
    mediaType: "video",
    mediaVideoSrc: "/21617-319452308_medium.mp4",
    mediaLabel: "Clinical Patient Consultation",
  },
  {
    id: "scene-5",
    avatar: { name: "Dr. Maya Chen · clinical and warm", role: "Consultant Dermatologist", position: "bottom-left", scale: 0.58 },
    shots: [
      { id: "s5-a", index: 1, startAt: 0,   endAt: 6.4, label: "The next step",     transitionIn: "Cut", narrationFragment: 'Review the full Prescribing Information,', visualStory: 'Closing copy on a quiet frame with no media behind it.' },
      { id: "s5-b", index: 2, startAt: 6.4, endAt: 8.0, label: "Fade to fair balance", transitionIn: "Fade out 400ms", narrationFragment: 'then consider whether DERMORA is appropriate for your patients.', visualStory: 'Everything fades toward black behind the fair-balance line.' },
    ],
    timings: [
      { elementId: "headline",  inAt: 0.4, outAt: 6.4, transitionIn: "Fade up 320ms", transitionOut: "Fade out 400ms" },
      { elementId: "narration", inAt: 0.8, outAt: 8.0, transitionIn: "Word-by-word reveal", transitionOut: "Hold to cut" },
      { elementId: "background", inAt: 0, outAt: 8.0, transitionIn: "Cut", transitionOut: "Fade to black 600ms" },
      { elementId: "voiceover", inAt: 0.8, outAt: 8.0, transitionIn: "Fade in 200ms", transitionOut: "Fade out 600ms" },
      { elementId: "sfx", inAt: 6.4, outAt: 8.0, transitionIn: "Swell in 400ms", transitionOut: "Fade to silence" },
      { elementId: "avatar", inAt: 0.4, outAt: 8.0, transitionIn: "Fade up 320ms", transitionOut: "Fade to black 600ms" },
    ],
    number: 5,
    title: "A clearer next step",
    duration: 8,
    narration: "Review the full Prescribing Information, then consider whether DERMORA is appropriate for your patients.",
    visual: "The pathway resolves into the brand mark, fair-balance area, and HCP call to action.",
    negativeVisual: "Missing fair balance box, unreadable ISI text, informal fonts.",
    claim: "Call to action",
    evidenceState: "approved",
    narrativeTag: "Outro",
    mediaType: "none",
  },
];
