import type { LibraryProduct } from "@/features/product-library/product-library-types";

export const PRODUCTS: LibraryProduct[] = [
  {
    id: "affolmy",
    name: "Affolmy",
    genericName: "Olmesartan",
    type: "Device",
    gradient: "linear-gradient(150deg,#4338ca,#6d5ef5 55%,#9b8cff)",
    dossiersVerified: 3,
    dossiersTotal: 6,
    claimsApproved: 112,
    views: 5,
    updated: "Sep 7, 2026",
  },
  {
    id: "abdec",
    name: "Abdec",
    genericName: "Amoxicillin",
    type: "Syrup",
    gradient: "linear-gradient(150deg,#c2620a,#e08a2b 55%,#f3ad55)",
    dossiersVerified: 2,
    dossiersTotal: 4,
    claimsApproved: 68,
    views: 3,
    updated: "Sep 5, 2026",
  },
  {
    id: "velmora",
    name: "Velmora",
    genericName: "Velmoxaban mesylate",
    type: "Tablet",
    gradient: "linear-gradient(150deg,#1b2a4a,#2f4a7d 55%,#5b7fb8)",
    dossiersVerified: 4,
    dossiersTotal: 4,
    claimsApproved: 214,
    views: 12,
    updated: "Today, 9:15 AM",
  },
  {
    id: "onkavia",
    name: "Onkavia",
    genericName: "Onkatrelinib dihydrochloride",
    type: "Injection",
    gradient: "linear-gradient(150deg,#3a1e4d,#63307a 55%,#a06bc4)",
    dossiersVerified: 3,
    dossiersTotal: 5,
    claimsApproved: 186,
    views: 8,
    updated: "Yesterday, 4:30 PM",
  },
  {
    id: "nirvexa",
    name: "Nirvexa",
    genericName: "Nirvexizumab-qfvd",
    type: "Injection",
    gradient: "linear-gradient(150deg,#12332c,#1d5a4a 55%,#3f9c7f)",
    dossiersVerified: 6,
    dossiersTotal: 6,
    claimsApproved: 162,
    views: 15,
    updated: "3 days ago",
  },
  {
    id: "dermora",
    name: "Dermora",
    genericName: "Dermoclizine fumarate",
    type: "Capsule",
    gradient: "linear-gradient(150deg,#7a1f06,#b82f0c 55%,#ff8a4c)",
    dossiersVerified: 1,
    dossiersTotal: 3,
    claimsApproved: 44,
    views: 2,
    updated: "1 week ago",
  },
  {
    id: "pulmavia",
    name: "Pulmavia",
    genericName: "Pulmavatinib citrate",
    type: "Device",
    gradient: "linear-gradient(150deg,#0e4d64,#1c7e9c 55%,#5cc3d9)",
    dossiersVerified: 5,
    dossiersTotal: 5,
    claimsApproved: 230,
    views: 9,
    updated: "Curated sample",
  },
  {
    id: "renalis",
    name: "Renalis",
    genericName: "Renalisertib sodium",
    type: "Tablet",
    gradient: "linear-gradient(150deg,#5b2c0e,#9c5220 55%,#dba05e)",
    dossiersVerified: 0,
    dossiersTotal: 2,
    claimsApproved: 0,
    views: 1,
    updated: "New",
  },
];
