export type RegulatoryBody = "FDA" | "EMA" | "MHRA" | "PMDA";

export interface DossierSource {
  id: string;
  name: string;
  type: "label" | "pubmed" | "clinical-trials" | "heor" | "slides";
  date: string;
  status: "approved" | "reference-only" | "under-review";
  details: string;
  citationCount: number;
}

export interface CitedClaim {
  id: string;
  text: string;
  sourceId: string;
  sourceName: string;
  confidence: number;
  isHeldOut?: boolean;
  heldOutReason?: string;
}

export interface UnverifiedClaim {
  id: string;
  claim: string;
  issue: string;
  sourceLink: string;
  status: "pending" | "accepted" | "rejected";
}

export interface DossierSection {
  id: string;
  number: number;
  title: string;
  category: "clinical" | "commercial" | "regulatory" | "safety";
  content: string;
  claimsCount: number;
  heldOutCount: number;
  citations: string[];
  unverifiedClaims?: UnverifiedClaim[];
}

export type ApprovalStatus = "pending" | "reviewing" | "approved" | "changes-requested";

export interface DossierApproval {
  role: string;
  name: string;
  initials: string;
  gradient: string;
  status: ApprovalStatus;
}

export type DocumentType = "commercial" | "patient-medication" | "hcp-scientific";

export interface BrandDossier {
  id: string;
  brandName: string;
  genericName: string;
  indication: string;
  therapyArea: string;
  regulatoryAnchor: RegulatoryBody;
  documentType: DocumentType;
  gradient: string;
  accentColor: string;
  initials: string;
  sectionsCount: number;
  claimsCited: number;
  claimsHeldOut: number;
  sourcesCount: number;
  lastUpdated: string;
  status: "complete" | "draft" | "updating" | "pending-approval";
  healthStatus?: "critical" | "warning" | "healthy";
  verifiedClaimsCount?: number;
  totalClaimsCount?: number;
  isSample?: boolean;
  /** How this dossier is classified — e.g. "Patient Related", "HCP Related". */
  category?: string;
  /** Who this dossier's content is ultimately written for. */
  targetAudience?: string[];
  /** Whether this dossier's sections were generated by the AI Brand
   *  Dossier Generator or the offline mock fallback. */
  generatedBy?: "ai" | "mock";
  sources: DossierSource[];
  sections: DossierSection[];
  /** Who needs to sign off before this dossier can be used to create content. */
  approvals: DossierApproval[];
}

/** An entry in the brand picker — not every brand has a dossier yet. */
export interface BrandOption {
  id: string;
  name: string;
  genericName: string;
  therapyArea: string;
  regulatoryAnchor: RegulatoryBody;
  hasDossier: boolean;
}

export type DossierWizardStep =
  | "list"
  | "product"
  | "sources"
  | "plan"
  | "writing"
  | "approval"
  | "view";
