import type { BrandDossier, BrandOption, DossierApproval } from "@/features/dossiers/dossier-types";

/** Every brand on file — some already have a dossier, some don't yet. */
export const BRAND_REGISTRY: BrandOption[] = [
  { id: "velmora", name: "Velmora", genericName: "velmoxaban mesylate", therapyArea: "Cardiology", regulatoryAnchor: "FDA", hasDossier: true },
  { id: "onkavia", name: "Onkavia", genericName: "onkatrelinib dihydrochloride", therapyArea: "Oncology", regulatoryAnchor: "EMA", hasDossier: true },
  { id: "nirvexa", name: "Nirvexa", genericName: "nirvexizumab-qfvd", therapyArea: "Immunology", regulatoryAnchor: "MHRA", hasDossier: true },
  { id: "dermora", name: "Dermora", genericName: "dermoclizine fumarate", therapyArea: "Dermatology", regulatoryAnchor: "FDA", hasDossier: false },
  { id: "pulmavia", name: "Pulmavia", genericName: "pulmavatinib citrate", therapyArea: "Respiratory", regulatoryAnchor: "FDA", hasDossier: false },
  { id: "renalis", name: "Renalis", genericName: "renalisertib sodium", therapyArea: "Nephrology", regulatoryAnchor: "PMDA", hasDossier: false },
];

/** Fresh copy of a fully-signed-off approval trail, for dossiers seeded as already live. */
function approvedByTeam(): DossierApproval[] {
  return [
    { role: "Medical Writer", name: "Medical Writer", initials: "MW", gradient: "linear-gradient(140deg,#ff7a3d,#c9310a)", status: "approved" },
    { role: "MLR Reviewer", name: "MLR Reviewer", initials: "MR", gradient: "linear-gradient(140deg,#22c07a,#12784a)", status: "approved" },
    { role: "Project Manager", name: "Project Manager", initials: "PM", gradient: "linear-gradient(140deg,#9b6bff,#5b21b6)", status: "approved" },
    { role: "Brand Lead", name: "You", initials: "N", gradient: "linear-gradient(140deg,#3a3f4b,#0d1017)", status: "approved" },
  ];
}

/** Fresh copy of an unstarted approval trail, for a dossier that hasn't been reviewed yet. */
function pendingApprovals(): DossierApproval[] {
  return approvedByTeam().map((a) => ({ ...a, status: "pending" as const }));
}

export const MOCK_DOSSIERS: BrandDossier[] = [
  {
    id: "velmora",
    brandName: "Velmora",
    genericName: "velmoxaban mesylate",
    indication: "Secondary prevention of atherosclerotic cardiovascular events in high-risk post-ACS adults",
    therapyArea: "Cardiology",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#1b2a4a,#2f4a7d 50%,#5b7fb8)",
    accentColor: "#ef4444",
    initials: "VL",
    sectionsCount: 18,
    claimsCited: 2,
    claimsHeldOut: 64,
    verifiedClaimsCount: 2,
    totalClaimsCount: 66,
    healthStatus: "critical",
    sourcesCount: 8,
    lastUpdated: "Today, 09:15 AM",
    status: "draft",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-fda",
        name: "FDA Approved Prescribing Information (Rev. 04/2026)",
        type: "label",
        date: "Apr 2026",
        status: "approved",
        details: "Section 1 Indications, Section 2 Dosage, Section 14 Clinical Studies",
        citationCount: 112,
      },
      {
        id: "src-clarity",
        name: "CLARITY-CV Phase III Pivotal Trial (N Engl J Med 2025; 392:101-114)",
        type: "pubmed",
        date: "Oct 2025",
        status: "approved",
        details: "N=12,480 patients, Primary Composite MACE endpoint HR 0.76 (95% CI 0.68-0.85; p<0.001)",
        citationCount: 64,
      },
      {
        id: "src-clinicaltrials",
        name: "ClinicalTrials.gov Protocol Identifier NCT04892110",
        type: "clinical-trials",
        date: "Jan 2026",
        status: "approved",
        details: "Double-blind, event-driven randomized international study",
        citationCount: 18,
      },
      {
        id: "src-heor",
        name: "Global HEOR Budget Impact & QALY Analysis Dossier",
        type: "heor",
        date: "Feb 2026",
        status: "approved",
        details: "ICER $42,500/QALY vs SOC; 14% net reduction in 30-day readmission penalties",
        citationCount: 20,
      },
    ],
    sections: [
      {
        id: "sec-1",
        number: 1,
        title: "Executive Summary & Clinical Rationale",
        category: "commercial",
        content: "Velmora (velmoxaban mesylate) is a next-generation selective direct inhibitor engineered for targeted secondary prevention in post-ACS patients. Across the pivotal CLARITY-CV study, co-administration with low-dose aspirin demonstrated a 24% relative risk reduction in major adverse cardiovascular events (MACE) compared with standard of care.",
        claimsCount: 8,
        heldOutCount: 1,
        citations: ["FDA Approved Prescribing Information (Rev. 04/2026)", "CLARITY-CV Phase III (NEJM 2025)"],
      },
      {
        id: "sec-2",
        number: 2,
        title: "Mechanism of Action & Dual Pathway Inhibition",
        category: "clinical",
        content: "Velmora selectively binds the catalytic pocket with sub-nanomolar affinity (Ki = 0.42 nM), attenuating downstream thrombin generation without disrupting baseline platelet adhesion in undamaged microvasculature. Dual pathway inhibition suppresses both platelet activation and fibrin network formation.",
        claimsCount: 16,
        heldOutCount: 14,
        citations: ["FDA PI Section 12.1", "Journal of Thrombosis & Haemostasis 2025"],
        unverifiedClaims: [
          {
            id: "uv-1",
            claim: "Selectively binds catalytic pocket with sub-nanomolar affinity (Ki = 0.42 nM) with zero off-target microvascular bleeding.",
            issue: "Absolute safety statement 'zero off-target bleeding' exceeds current FDA Section 12.1 label scope. Must be qualified.",
            sourceLink: "FDA PI §12.1 (p. 14)",
            status: "pending",
          },
          {
            id: "uv-2",
            claim: "Dual pathway inhibition reduces secondary ischemic stroke recurrence by 34% in diabetic subgroup.",
            issue: "Subgroup analysis was exploratory and not pre-specified in primary statistical plan of CLARITY-CV.",
            sourceLink: "CLARITY-CV Subgroup Analysis Table S4",
            status: "pending",
          },
          {
            id: "uv-3",
            claim: "Superior pharmacokinetic half-life allows forgiving once-daily dosing window up to 36 hours.",
            issue: "Dosing flexibility beyond 24 hours is unapproved by regulatory bodies and constitutes off-label guidance.",
            sourceLink: "FDA PI §2.1 Dosing and Administration",
            status: "pending",
          },
        ],
      },
      {
        id: "sec-3",
        number: 3,
        title: "Pivotal Phase III Efficacy (CLARITY-CV)",
        category: "clinical",
        content: "In the randomized, double-blind CLARITY-CV trial (N=12,480), Velmora achieved its primary composite endpoint of CV death, myocardial infarction, or stroke (HR 0.76; 95% CI: 0.68–0.85; p < 0.001). Risk divergence was evident by day 30 and sustained through median 28-month follow-up.",
        claimsCount: 28,
        heldOutCount: 26,
        citations: ["CLARITY-CV Phase III (NEJM 2025; 392:101-114)", "NCT04892110"],
        unverifiedClaims: [
          {
            id: "uv-4",
            claim: "Achieves statistically superior 5-year overall survival over standard ticagrelor regimens.",
            issue: "Trial median follow-up was 28 months; 5-year data extrapolation is unverified.",
            sourceLink: "CLARITY-CV NEJM 2025; 392:101-114",
            status: "pending",
          },
        ],
      },
      {
        id: "sec-4",
        number: 4,
        title: "Safety Profile & Bleeding Adjudication",
        category: "safety",
        content: "Major TIMI bleeding occurred in 1.9% of Velmora-treated patients vs 1.4% in the placebo group (HR 1.34; 95% CI: 0.98–1.82; p = 0.06). Fatal or intracranial hemorrhage rates showed no statistically significant difference between arms (0.2% vs 0.2%).",
        claimsCount: 22,
        heldOutCount: 18,
        citations: ["FDA PI Section 6.1 Adverse Reactions", "CLARITY-CV Safety Appendix"],
      },
      {
        id: "sec-5",
        number: 5,
        title: "Dosing, Administration & Renal Guidance",
        category: "regulatory",
        content: "The recommended dose is 15 mg once daily taken orally with or without food. In patients with moderate renal impairment (eGFR 30–59 mL/min/1.73m²), no dosage adjustment is required. Not recommended for eGFR < 15 mL/min.",
        claimsCount: 14,
        heldOutCount: 5,
        citations: ["FDA PI Section 2.1 & 8.6"],
      },
    ],
  },
  {
    id: "onkavia",
    brandName: "Onkavia",
    genericName: "onkatrelinib dihydrochloride",
    indication: "First-line treatment of adult patients with metastatic RET fusion-positive NSCLC",
    therapyArea: "Oncology",
    regulatoryAnchor: "EMA",
    gradient: "linear-gradient(145deg,#3a1e4d,#63307a 50%,#a06bc4)",
    accentColor: "#eab308",
    initials: "OK",
    sectionsCount: 19,
    claimsCited: 42,
    claimsHeldOut: 42,
    verifiedClaimsCount: 42,
    totalClaimsCount: 84,
    healthStatus: "warning",
    sourcesCount: 7,
    lastUpdated: "Yesterday, 04:30 PM",
    status: "draft",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-ema",
        name: "EMA Summary of Product Characteristics (SmPC 2026)",
        type: "label",
        date: "Mar 2026",
        status: "approved",
        details: "Section 4.1 Therapeutic Indications, Section 5.1 Pharmacodynamic properties",
        citationCount: 96,
      },
      {
        id: "src-target-trial",
        name: "TARGET-LUNG Phase III Trial (Lancet Oncology 2025)",
        type: "pubmed",
        date: "Dec 2025",
        status: "approved",
        details: "N=340, Progression-Free Survival (PFS) HR 0.44 (95% CI 0.33-0.59; p<0.0001)",
        citationCount: 58,
      },
    ],
    sections: [
      {
        id: "sec-o1",
        number: 1,
        title: "Indication & Biomarker Screening",
        category: "clinical",
        content: "Onkavia is indicated as monotherapy for treatment-naïve adult patients with RET fusion-positive advanced non-small cell lung cancer, validated via next-generation sequencing (NGS) or RT-PCR.",
        claimsCount: 12,
        heldOutCount: 6,
        citations: ["EMA SmPC Section 4.1", "ESMO Clinical Guidelines 2025"],
      },
      {
        id: "sec-o2",
        number: 2,
        title: "Progression-Free Survival & Intracranial Response",
        category: "clinical",
        content: "In the pivotal TARGET-LUNG study, Onkavia demonstrated median PFS of 24.8 months vs 11.2 months with platinum doublet chemotherapy (HR 0.44, p < 0.0001). Confirmed intracranial overall response rate in CNS metastases reached 82%.",
        claimsCount: 24,
        heldOutCount: 12,
        citations: ["Lancet Oncology 2025", "TARGET-LUNG Clinical Study Report"],
        unverifiedClaims: [
          {
            id: "uv-o1",
            claim: "Reduces risk of central nervous system progression by 76% across all metastatic RET cohorts.",
            issue: "Intracranial progression metric requires audit against independent blinded radiological review committee (BICR) dataset.",
            sourceLink: "TARGET-LUNG CNS Protocol Appendix 3",
            status: "pending",
          },
        ],
      },
    ],
  },
  {
    id: "nirvexa",
    brandName: "Nirvexa",
    genericName: "nirvexizumab-qfvd",
    indication: "Treatment of moderate-to-severe active ulcerative colitis in adults",
    therapyArea: "Immunology",
    regulatoryAnchor: "MHRA",
    gradient: "linear-gradient(145deg,#12332c,#1d5a4a 50%,#3f9c7f)",
    accentColor: "#10b981",
    initials: "NX",
    sectionsCount: 16,
    claimsCited: 162,
    claimsHeldOut: 38,
    sourcesCount: 6,
    lastUpdated: "3 days ago",
    status: "complete",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-mhra",
        name: "MHRA Approved Product Information",
        type: "label",
        date: "Jan 2026",
        status: "approved",
        details: "Full marketing authorisation documentation for Great Britain",
        citationCount: 88,
      },
    ],
    sections: [
      {
        id: "sec-n1",
        number: 1,
        title: "Mucosal Healing & Clinical Remission",
        category: "clinical",
        content: "Nirvexa induced endoscopic mucosal healing at Week 12 in 58% of biologic-experienced patients, maintaining steroid-free remission through Week 52 in 67% of responders.",
        claimsCount: 18,
        heldOutCount: 3,
        citations: ["Gastroenterology 2025", "MHRA SmPC Section 5.1"],
      },
    ],
  },
  {
    id: "cardioxa",
    brandName: "Cardioxa",
    genericName: "levomilnacipran ER",
    indication: "Major depressive disorder in adults with cognitive fatigue symptoms",
    therapyArea: "Neuropsychiatry",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#2f1e4a,#4b2c78 50%,#7c4bb8)",
    accentColor: "#f97316",
    initials: "CX",
    sectionsCount: 17,
    claimsCited: 165,
    claimsHeldOut: 0,
    verifiedClaimsCount: 165,
    totalClaimsCount: 165,
    healthStatus: "healthy",
    sourcesCount: 5,
    lastUpdated: "Curated Sample",
    status: "complete",
    isSample: true,
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-cx-fda",
        name: "FDA Prescribing Information (NDA 204153)",
        type: "label",
        date: "Jan 2026",
        status: "approved",
        details: "Section 1 & Section 14 Efficacy Trials",
        citationCount: 92,
      },
    ],
    sections: [
      {
        id: "sec-cx1",
        number: 1,
        title: "Clinical Need & Dual Neurotransmitter Modulation",
        category: "clinical",
        content: "Cardioxa selectively inhibits norepinephrine and serotonin reuptake (2:1 ratio) demonstrating significant reductions in Montgomery-Åsberg Depression Rating Scale (MADRS) at 8 weeks.",
        claimsCount: 14,
        heldOutCount: 0,
        citations: ["FDA PI §1", "Journal of Clinical Psychiatry 2025"],
      },
    ],
  },
  {
    id: "pulmovax",
    brandName: "PulmoVax",
    genericName: "albuterol / budesonide",
    indication: "Fixed-dose dual bronchodilator / ICS combination for asthma maintenance",
    therapyArea: "Respiratory",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#133b34,#1c6356 50%,#349e8a)",
    accentColor: "#0ea5e9",
    initials: "PV",
    sectionsCount: 21,
    claimsCited: 230,
    claimsHeldOut: 0,
    verifiedClaimsCount: 230,
    totalClaimsCount: 230,
    healthStatus: "healthy",
    sourcesCount: 9,
    lastUpdated: "Curated Sample",
    status: "complete",
    isSample: true,
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-pv-label",
        name: "Global WHO / FDA Monograph & Pivotal MANDALA Phase III",
        type: "label",
        date: "Feb 2026",
        status: "approved",
        details: "Pivotal MANDALA & DENALI clinical readouts",
        citationCount: 138,
      },
    ],
    sections: [
      {
        id: "sec-pv1",
        number: 1,
        title: "Annualized Severe Exacerbation Risk Divergence",
        category: "clinical",
        content: "Fixed combination albuterol/budesonide reduced risk of severe exacerbations by 27% compared with albuterol monotherapy in patients with moderate-to-severe asthma.",
        claimsCount: 22,
        heldOutCount: 0,
        citations: ["MANDALA Trial NEJM", "FDA Full USPI"],
      },
    ],
  },
];

export const NEW_DOSSIER_TEMPLATE: BrandDossier = {
  id: "aveloxa",
  brandName: "Aveloxa",
  genericName: "aveloxotide dipropionate",
  indication: "Maintenance therapy for severe eosinophilic asthma in patients aged 12 and older",
  therapyArea: "Respiratory",
  regulatoryAnchor: "FDA",
  gradient: "linear-gradient(145deg,#ff5b2d,#fd4816 50%,#b82f0c)",
  accentColor: "#fd4816",
  initials: "AV",
  sectionsCount: 18,
  claimsCited: 187,
  claimsHeldOut: 3,
  sourcesCount: 1,
  lastUpdated: "Just now",
  status: "complete",
  documentType: "commercial",
  approvals: pendingApprovals(),
  // Only the label ships pre-verified — the rest of the regulatory
  // checklist (clinical trial record, pivotal publication, HEOR,
  // congress deck) starts pending so the Sources step's upload
  // checklist has real work to demonstrate.
  sources: [
    {
      id: "av-label",
      name: "FDA Prescribing Information (Rev. 01/2026)",
      type: "label",
      date: "Jan 2026",
      status: "approved",
      details: "Full US Prescribing Information including Highlights and Section 14",
      citationCount: 94,
    },
  ],
  sections: [
    {
      id: "sec-a1",
      number: 1,
      title: "Executive Summary & Clinical Need",
      category: "commercial",
      content: "Aveloxa (aveloxotide dipropionate) is a precision biologic engineered to selectively inhibit the IL-5Rα pathway, producing rapid and sustained depletion of circulating eosinophils in severe uncontrolled asthma.",
      claimsCount: 11,
      heldOutCount: 0,
      citations: ["FDA PI Section 1", "AURA-ASTHMA Phase III (NEJM 2025)"],
    },
    {
      id: "sec-a2",
      number: 2,
      title: "Exacerbation Reduction & Lung Function",
      category: "clinical",
      content: "In patients with baseline blood eosinophils ≥ 300 cells/µL, Aveloxa demonstrated a 68% reduction in annualized asthma exacerbation rates (AAER) vs placebo (rate ratio 0.32; 95% CI: 0.25–0.41; p < 0.0001). Pre-bronchodilator FEV1 improved by +240 mL at Week 52.",
      claimsCount: 26,
      heldOutCount: 1,
      citations: ["AURA-ASTHMA Phase III (NEJM 2025)", "ClinicalTrials.gov NCT05118942"],
    },
    {
      id: "sec-a3",
      number: 3,
      title: "Mechanism of Action & Target Specificity",
      category: "clinical",
      content: "Aveloxa binds domain 1 of the IL-5 receptor alpha chain with high selectivity (Kd = 12 pM), directing antibody-dependent cell-mediated cytotoxicity (ADCC) to eliminate eosinophils and basophils within 24 hours of first administration.",
      claimsCount: 18,
      heldOutCount: 0,
      citations: ["FDA PI Section 12.1", "Journal of Allergy and Clinical Immunology 2025"],
    },
    {
      id: "sec-a4",
      number: 4,
      title: "Safety, Tolerability & Immunogenicity",
      category: "safety",
      content: "The most common adverse reactions (incidence ≥ 3% and greater than placebo) were nasopharyngitis (6.4% vs 5.8%) and headache (4.2% vs 3.6%). Neutralizing anti-drug antibody incidence was under 1.2% through 52 weeks.",
      claimsCount: 19,
      heldOutCount: 1,
      citations: ["FDA PI Section 6.1 Adverse Reactions"],
    },
    {
      id: "sec-a5",
      number: 5,
      title: "Dosage, Delivery & Prefilled Pen",
      category: "regulatory",
      content: "Administered as 30 mg subcutaneously once every 4 weeks using a single-dose autoinjector prefilled pen, designed for at-home patient administration following HCP training.",
      claimsCount: 12,
      heldOutCount: 0,
      citations: ["FDA PI Section 2 Dosage and Administration"],
    },
  ],
};
