import type { BrandDossier, BrandOption, DossierApproval } from "@/features/dossiers/dossier-types";

/** Every brand on file — some already have a dossier, some don't yet. */
export const BRAND_REGISTRY: BrandOption[] = [
  { id: "velmora", name: "Velmora", genericName: "velmoxaban mesylate", therapyArea: "Cardiology", regulatoryAnchor: "FDA", hasDossier: true },
  { id: "onkavia", name: "Onkavia", genericName: "onkatrelinib dihydrochloride", therapyArea: "Oncology", regulatoryAnchor: "EMA", hasDossier: true },
  { id: "nirvexa", name: "Nirvexa", genericName: "nirvexizumab-qfvd", therapyArea: "Immunology", regulatoryAnchor: "MHRA", hasDossier: true },
  { id: "dermora", name: "Dermora", genericName: "dermoclizine fumarate", therapyArea: "Dermatology", regulatoryAnchor: "FDA", hasDossier: false },
  { id: "pulmavia", name: "Pulmavia", genericName: "pulmavatinib citrate", therapyArea: "Respiratory", regulatoryAnchor: "FDA", hasDossier: false },
  { id: "renalis", name: "Renalis", genericName: "renalisertib sodium", therapyArea: "Nephrology", regulatoryAnchor: "PMDA", hasDossier: false },
];

/** Fresh copy of a fully-signed-off approval trail, for dossiers seeded as already live. */
function approvedByTeam(): DossierApproval[] {
  return [
    { role: "Medical Writer", name: "Medical Writer", initials: "MW", gradient: "linear-gradient(140deg,#ff7a3d,#c9310a)", status: "approved" },
    { role: "MLR Reviewer", name: "MLR Reviewer", initials: "MR", gradient: "linear-gradient(140deg,#22c07a,#12784a)", status: "approved" },
    { role: "Project Manager", name: "Project Manager", initials: "PM", gradient: "linear-gradient(140deg,#9b6bff,#5b21b6)", status: "approved" },
    { role: "Brand Lead", name: "You", initials: "N", gradient: "linear-gradient(140deg,#3a3f4b,#0d1017)", status: "approved" },
  ];
}

/** Fresh copy of an unstarted approval trail, for a dossier that hasn't been reviewed yet. */
function pendingApprovals(): DossierApproval[] {
  return approvedByTeam().map((a) => ({ ...a, status: "pending" as const }));
}

export const MOCK_DOSSIERS: BrandDossier[] = [
  {
    id: "velmora",
    brandName: "Velmora",
    genericName: "velmoxaban mesylate",
    indication: "Secondary prevention of atherosclerotic cardiovascular events in high-risk post-ACS adults",
    therapyArea: "Cardiology",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#1b2a4a,#2f4a7d 50%,#5b7fb8)",
    accentColor: "#ef4444",
    initials: "VL",
    sectionsCount: 18,
    claimsCited: 2,
    claimsHeldOut: 64,
    verifiedClaimsCount: 2,
    totalClaimsCount: 66,
    healthStatus: "critical",
    sourcesCount: 8,
    lastUpdated: "Today, 09:15 AM",
    status: "draft",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-fda",
        name: "FDA Approved Prescribing Information (Rev. 04/2026)",
        type: "label",
        date: "Apr 2026",
        status: "approved",
        details: "Section 1 Indications, Section 2 Dosage, Section 14 Clinical Studies",
        citationCount: 112,
      },
      {
        id: "src-clarity",
        name: "CLARITY-CV Phase III Pivotal Trial (N Engl J Med 2025; 392:101-114)",
        type: "pubmed",
        date: "Oct 2025",
        status: "approved",
        details: "N=12,480 patients, Primary Composite MACE endpoint HR 0.76 (95% CI 0.68-0.85; p<0.001)",
        citationCount: 64,
      },
      {
        id: "src-clinicaltrials",
        name: "ClinicalTrials.gov Protocol Identifier NCT04892110",
        type: "clinical-trials",
        date: "Jan 2026",
        status: "approved",
        details: "Double-blind, event-driven randomized international study",
        citationCount: 18,
      },
      {
        id: "src-heor",
        name: "Global HEOR Budget Impact & QALY Analysis Dossier",
        type: "heor",
        date: "Feb 2026",
        status: "approved",
        details: "ICER $42,500/QALY vs SOC; 14% net reduction in 30-day readmission penalties",
        citationCount: 20,
      },
    ],
    sections: [
      {
        id: "sec-1",
        number: 1,
        title: "Executive Summary & Clinical Rationale",
        category: "commercial",
        content: "Velmora (velmoxaban mesylate) is a next-generation selective direct inhibitor engineered for targeted secondary prevention in post-ACS patients. Across the pivotal CLARITY-CV study, co-administration with low-dose aspirin demonstrated a 24% relative risk reduction in major adverse cardiovascular events (MACE) compared with standard of care. The treatment effect was consistent across the pre-specified subgroups, including patients with diabetes, chronic kidney disease and prior revascularisation, with no interaction reaching nominal significance.\n\nThe programme was designed around a question the existing class could not answer: whether the ischaemic benefit of intensified antithrombotic therapy can be separated from its bleeding cost. Velmora addresses that separation pharmacologically rather than by dose reduction, binding a single catalytic site while leaving the haemostatic response to vessel injury intact. Bleeding of any severity occurred at a rate comparable to standard of care, and no excess of intracranial or fatal bleeding was observed.\n\nThis dossier collects the evidence behind every statement the commercial and medical teams may make about that position. Each section states what is established, the strength of the evidence behind it, and the boundary past which a claim would leave the approved label. Where the data supports a direction but not a conclusion, the section says so.",
        claimsCount: 8,
        heldOutCount: 1,
        citations: ["FDA Approved Prescribing Information (Rev. 04/2026)", "CLARITY-CV Phase III (NEJM 2025)"],
      },
      {
        id: "sec-2",
        number: 2,
        title: "Mechanism of Action & Dual Pathway Inhibition",
        category: "clinical",
        content: "Velmora selectively binds the catalytic pocket with sub-nanomolar affinity (Ki = 0.42 nM), attenuating downstream thrombin generation without disrupting baseline platelet adhesion in undamaged microvasculature. Dual pathway inhibition suppresses both platelet activation and fibrin network formation.\n\nSelectivity was profiled against a panel of 68 related serine proteases. Measurable inhibition was confined to the intended target at concentrations up to one hundred times the therapeutic exposure, and no activity was detected against the proteases governing normal wound healing. This is the mechanistic basis for the bleeding profile described in Section 4, and it is the reason the label does not require a dose reduction in patients at elevated bleeding risk.\n\nEx vivo work in human keratinocyte and endothelial assays confirmed that phosphorylation blockade is reversible and concentration-dependent, returning to baseline within two half-lives of withdrawal. Onset of measurable pharmacodynamic effect is within ninety minutes of the first oral dose, which is consistent with the divergence in event curves seen from day 30 in the pivotal trial.",
        claimsCount: 16,
        heldOutCount: 14,
        citations: ["FDA PI Section 12.1", "Journal of Thrombosis & Haemostasis 2025"],
        unverifiedClaims: [
          {
            id: "uv-1",
            claim: "Selectively binds catalytic pocket with sub-nanomolar affinity (Ki = 0.42 nM) with zero off-target microvascular bleeding.",
            issue: "Absolute safety statement 'zero off-target bleeding' exceeds current FDA Section 12.1 label scope. Must be qualified.",
            sourceLink: "FDA PI §12.1 (p. 14)",
            status: "pending",
          },
          {
            id: "uv-2",
            claim: "Dual pathway inhibition reduces secondary ischemic stroke recurrence by 34% in diabetic subgroup.",
            issue: "Subgroup analysis was exploratory and not pre-specified in primary statistical plan of CLARITY-CV.",
            sourceLink: "CLARITY-CV Subgroup Analysis Table S4",
            status: "pending",
          },
          {
            id: "uv-3",
            claim: "Superior pharmacokinetic half-life allows forgiving once-daily dosing window up to 36 hours.",
            issue: "Dosing flexibility beyond 24 hours is unapproved by regulatory bodies and constitutes off-label guidance.",
            sourceLink: "FDA PI §2.1 Dosing and Administration",
            status: "pending",
          },
        ],
      },
      {
        id: "sec-3",
        number: 3,
        title: "Pivotal Phase III Efficacy (CLARITY-CV)",
        category: "clinical",
        content: "In the randomized, double-blind CLARITY-CV trial (N=12,480), Velmora achieved its primary composite endpoint of CV death, myocardial infarction, or stroke (HR 0.76; 95% CI: 0.68–0.85; p < 0.001). Risk divergence was evident by day 30 and sustained through median 28-month follow-up.\n\nEach component of the composite moved in the same direction. Cardiovascular death was reduced (HR 0.81; 95% CI: 0.69–0.95), as were myocardial infarction (HR 0.74; 95% CI: 0.63–0.87) and ischaemic stroke (HR 0.71; 95% CI: 0.56–0.90). No component moved against the composite, which is what allows the primary result to be described as a treatment effect rather than an artefact of one dominant endpoint.\n\nThe trial enrolled across 41 countries and 620 sites, with an enrolled population whose median age was 64 and of whom 38% were women. Adherence exceeded 92% in both arms and fewer than 1% of participants were lost to follow-up, so the estimate is not materially sensitive to assumptions about missing data.",
        claimsCount: 28,
        heldOutCount: 26,
        citations: ["CLARITY-CV Phase III (NEJM 2025; 392:101-114)", "NCT04892110"],
        subsections: [
          { id: "sec-3-1", number: 1, title: "Trial design and population", content: "CLARITY-CV randomised 12,480 adults with an acute coronary syndrome in the preceding twelve months, 1:1, double-blind, across 41 countries and 620 sites. Background low-dose aspirin was mandatory in both arms, so the comparison is Velmora added to standard of care rather than Velmora against it.\n\nMedian age was 64, 38% of participants were women, and 31% had diabetes at entry. Adherence exceeded 92% in both arms and fewer than 1% were lost to follow-up, which is what allows the primary estimate to be quoted without a sensitivity caveat." },
          { id: "sec-3-2", number: 2, title: "Primary composite endpoint", content: "The primary endpoint was the first occurrence of cardiovascular death, myocardial infarction or stroke. Velmora reduced it from 11.8% to 9.1% over a median 28 months (HR 0.76; 95% CI 0.68–0.85; p < 0.001), with the curves separating by day 30 and continuing to diverge to the end of follow-up.\n\nThe absolute risk reduction of 2.7 percentage points corresponds to a number needed to treat of 37 over the trial period. Both the relative and the absolute figure are on the label and either may be used, but a relative figure presented without the absolute one overstates the effect and will not clear review." },
          { id: "sec-3-3", number: 3, title: "Component and subgroup analyses", content: "Every component moved with the composite: cardiovascular death (HR 0.81; 95% CI 0.69–0.95), myocardial infarction (HR 0.74; 95% CI 0.63–0.87) and ischaemic stroke (HR 0.71; 95% CI 0.56–0.90). No component moved against it, which is the basis for describing the result as a treatment effect rather than one dominant endpoint carrying the rest.\n\nTwelve subgroups were pre-specified and none showed an interaction reaching nominal significance. Subgroup figures are supportive only and may not be presented as evidence of benefit in a particular population." },
        ],
        unverifiedClaims: [
          {
            id: "uv-4",
            claim: "Achieves statistically superior 5-year overall survival over standard ticagrelor regimens.",
            issue: "Trial median follow-up was 28 months; 5-year data extrapolation is unverified.",
            sourceLink: "CLARITY-CV NEJM 2025; 392:101-114",
            status: "pending",
          },
        ],
      },
      {
        id: "sec-4",
        number: 4,
        title: "Safety Profile & Bleeding Adjudication",
        category: "safety",
        content: "Major TIMI bleeding occurred in 1.9% of Velmora-treated patients vs 1.4% in the placebo group (HR 1.34; 95% CI: 0.98–1.82; p = 0.06). Fatal or intracranial hemorrhage rates showed no statistically significant difference between arms (0.2% vs 0.2%).\n\nEvery suspected event was adjudicated by an independent clinical events committee blinded to treatment allocation, using the TIMI and BARC definitions in parallel so the result can be read against either scale. The confidence interval crosses one, and the section therefore describes the bleeding signal as not excluding a modest increase rather than as an established difference.\n\nDiscontinuation for bleeding of any severity was 2.6% versus 2.1%, and the median time to first event was 94 days. No subgroup, age above 75, weight below 60 kg, concomitant proton pump inhibitor use, showed an interaction that would justify a separate bleeding statement in promotional material.",
        claimsCount: 22,
        heldOutCount: 18,
        citations: ["FDA PI Section 6.1 Adverse Reactions", "CLARITY-CV Safety Appendix"],
        subsections: [
          { id: "sec-4-1", number: 1, title: "Bleeding events and adjudication", content: "Major TIMI bleeding occurred in 1.9% of Velmora-treated patients against 1.4% on placebo (HR 1.34; 95% CI 0.98–1.82; p = 0.06). Fatal and intracranial haemorrhage were equal between arms at 0.2%.\n\nEvery suspected event was adjudicated by an independent clinical events committee blinded to allocation, scored against the TIMI and BARC definitions in parallel so the result can be read on either scale. The confidence interval crosses one, so the finding is described as not excluding a modest increase, never as equivalence." },
          { id: "sec-4-2", number: 2, title: "Other adverse reactions", content: "Adverse reactions occurring in at least 2% of treated patients and more often than on placebo were dyspepsia (4.1% vs 3.2%), bruising (3.8% vs 2.4%) and epistaxis (2.6% vs 1.7%). None led to a dose change in more than 1% of participants.\n\nDiscontinuation for any adverse event was 6.2% against 5.4%. Hepatic enzyme elevations above three times the upper limit of normal occurred at the same rate in both arms, and the label carries no hepatic monitoring requirement." },
        ],
      },
      {
        id: "sec-5",
        number: 5,
        title: "Dosing, Administration & Renal Guidance",
        category: "regulatory",
        content: "The recommended dose is 15 mg once daily taken orally with or without food. In patients with moderate renal impairment (eGFR 30–59 mL/min/1.73m²), no dosage adjustment is required. Not recommended for eGFR < 15 mL/min.\n\nNo adjustment is required for age, sex, weight or mild hepatic impairment. In moderate hepatic impairment the exposure increase was 1.4-fold and the label advises clinical monitoring rather than a lower dose; in severe impairment the drug has not been studied and is not recommended. A missed dose should be taken on the same day and the schedule resumed the following morning; two doses must not be taken together.\n\nFor planned surgery with a moderate or high bleeding risk, the label directs interruption at least 48 hours before the procedure and restarting once haemostasis is secured. Switching from a vitamin K antagonist is done when the INR falls below 2.0. These are label instructions and may be stated as written; anything beyond them, including a bridging regimen, is outside the approved text.",
        claimsCount: 14,
        heldOutCount: 5,
        citations: ["FDA PI Section 2.1 & 8.6"],
        subsections: [
          { id: "sec-5-1", number: 1, title: "Renal and hepatic impairment", content: "No dosage adjustment is required in mild or moderate renal impairment (eGFR 30–59 mL/min/1.73m²). Below 15 mL/min the medicine has not been studied and is not recommended; between 15 and 29 the label advises clinical judgement rather than a defined reduction.\n\nMild hepatic impairment needs no adjustment. In moderate impairment exposure rose 1.4-fold and the label directs clinical monitoring rather than a lower dose. Severe impairment was not studied, and no dosing statement may be made for it." },
          { id: "sec-5-2", number: 2, title: "Missed dose and switching", content: "A missed dose should be taken the same day and the normal schedule resumed the following morning; two doses must never be taken together. This wording is on the label and may be reproduced verbatim in patient-facing material.\n\nSwitching from a vitamin K antagonist begins once the INR falls below 2.0. Switching from a parenteral anticoagulant begins at the time the next infusion would have been due. Anything beyond these two instructions, including a bridging regimen, is outside the approved text." },
          { id: "sec-5-3", number: 3, title: "Perioperative interruption", content: "For a procedure carrying a moderate or high bleeding risk, the label directs interruption at least 48 hours beforehand, and at least 24 hours for a low-risk procedure. Treatment restarts once haemostasis is secured.\n\nNo reversal agent is approved. In the event of significant bleeding the label directs discontinuation and standard supportive management, and promotional material may not imply that a reversal option exists." },
        ],
      },
    ],
  },
  {
    id: "onkavia",
    brandName: "Onkavia",
    genericName: "onkatrelinib dihydrochloride",
    indication: "First-line treatment of adult patients with metastatic RET fusion-positive NSCLC",
    therapyArea: "Oncology",
    regulatoryAnchor: "EMA",
    gradient: "linear-gradient(145deg,#3a1e4d,#63307a 50%,#a06bc4)",
    accentColor: "#eab308",
    initials: "OK",
    sectionsCount: 19,
    claimsCited: 42,
    claimsHeldOut: 42,
    verifiedClaimsCount: 42,
    totalClaimsCount: 84,
    healthStatus: "warning",
    sourcesCount: 7,
    lastUpdated: "Yesterday, 04:30 PM",
    status: "draft",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-ema",
        name: "EMA Summary of Product Characteristics (SmPC 2026)",
        type: "label",
        date: "Mar 2026",
        status: "approved",
        details: "Section 4.1 Therapeutic Indications, Section 5.1 Pharmacodynamic properties",
        citationCount: 96,
      },
      {
        id: "src-target-trial",
        name: "TARGET-LUNG Phase III Trial (Lancet Oncology 2025)",
        type: "pubmed",
        date: "Dec 2025",
        status: "approved",
        details: "N=340, Progression-Free Survival (PFS) HR 0.44 (95% CI 0.33-0.59; p<0.0001)",
        citationCount: 58,
      },
    ],
    sections: [
      {
        id: "sec-o1",
        number: 1,
        title: "Indication & Biomarker Screening",
        category: "clinical",
        content: "Onkavia is indicated as monotherapy for treatment-naïve adult patients with RET fusion-positive advanced non-small cell lung cancer, validated via next-generation sequencing (NGS) or RT-PCR.\n\nThe indication is tied to the biomarker, not to the histology alone: fusion status must be confirmed by an approved or validated assay before treatment is initiated, and the trial population was enrolled on that basis. Claims that describe the medicine as a treatment for advanced NSCLC without the fusion qualifier are outside the label.\n\nPrior systemic therapy for advanced disease was an exclusion in the pivotal study, so the treatment-naive wording is a description of the evidence rather than a preference between lines. The programme in previously treated patients is ongoing and no statement about that setting is supportable yet.",
        claimsCount: 12,
        heldOutCount: 6,
        citations: ["FDA PI Section 1 Indications and Usage", "NCCN Clinical Practice Guidelines (v3.2025)"],
      },
      {
        id: "sec-o2",
        number: 2,
        title: "Progression-Free Survival & Intracranial Response",
        category: "clinical",
        content: "In the pivotal TARGET-LUNG study, Onkavia demonstrated median PFS of 24.8 months vs 11.2 months with platinum doublet chemotherapy (HR 0.44, p < 0.0001). Confirmed intracranial overall response rate in CNS metastases reached 82%.\n\nThe progression-free survival benefit was consistent across the pre-specified subgroups, including patients with baseline CNS involvement, ECOG 0 versus 1, and both fusion partners represented in the study. Overall survival data were immature at the primary analysis and no survival claim may be made.\n\nResponses were durable: median duration of response had not been reached at the data cut, with 71% of responders still in response at eighteen months. Intracranial responses were assessed by blinded independent central review using RANO-BM, which is the standard the CNS figure should always be attributed to.",
        claimsCount: 24,
        heldOutCount: 12,
        citations: ["Lancet Oncology 2025", "TARGET-LUNG Clinical Study Report"],
        unverifiedClaims: [
          {
            id: "uv-o1",
            claim: "Reduces risk of central nervous system progression by 76% across all metastatic RET cohorts.",
            issue: "Intracranial progression metric requires audit against independent blinded radiological review committee (BICR) dataset.",
            sourceLink: "TARGET-LUNG CNS Protocol Appendix 3",
            status: "pending",
          },
        ],
      },
    ],
  },
  {
    id: "nirvexa",
    brandName: "Nirvexa",
    genericName: "nirvexizumab-qfvd",
    indication: "Treatment of moderate-to-severe active ulcerative colitis in adults",
    therapyArea: "Immunology",
    regulatoryAnchor: "MHRA",
    gradient: "linear-gradient(145deg,#12332c,#1d5a4a 50%,#3f9c7f)",
    accentColor: "#10b981",
    initials: "NX",
    sectionsCount: 16,
    claimsCited: 162,
    claimsHeldOut: 38,
    sourcesCount: 6,
    lastUpdated: "3 days ago",
    status: "complete",
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-mhra",
        name: "MHRA Approved Product Information",
        type: "label",
        date: "Jan 2026",
        status: "approved",
        details: "Full marketing authorisation documentation for Great Britain",
        citationCount: 88,
      },
    ],
    sections: [
      {
        id: "sec-n1",
        number: 1,
        title: "Mucosal Healing & Clinical Remission",
        category: "clinical",
        content: "Nirvexa induced endoscopic mucosal healing at Week 12 in 58% of biologic-experienced patients, maintaining steroid-free remission through Week 52 in 67% of responders.\n\nEndoscopic healing was scored centrally against the Mayo endoscopic subscore, with a score of zero or one counted as healing. The biologic-experienced population had failed a median of two prior advanced therapies, which is the comparison that makes the Week 12 figure meaningful and should accompany it wherever it is quoted.\n\nSteroid-free remission was defined as clinical remission with no corticosteroid exposure for at least twelve weeks before the Week 52 visit. Patients who required rescue therapy were counted as non-responders from the point of rescue onward, so the maintenance figure is not inflated by treatment switching.",
        claimsCount: 18,
        heldOutCount: 3,
        citations: ["Gastroenterology 2025", "FDA PI Section 12.1 Mechanism of Action"],
      },
    ],
  },
  {
    id: "cardioxa",
    brandName: "Cardioxa",
    genericName: "levomilnacipran ER",
    indication: "Major depressive disorder in adults with cognitive fatigue symptoms",
    therapyArea: "Neuropsychiatry",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#2f1e4a,#4b2c78 50%,#7c4bb8)",
    accentColor: "#f97316",
    initials: "CX",
    sectionsCount: 17,
    claimsCited: 165,
    claimsHeldOut: 0,
    verifiedClaimsCount: 165,
    totalClaimsCount: 165,
    healthStatus: "healthy",
    sourcesCount: 5,
    lastUpdated: "Curated Sample",
    status: "complete",
    isSample: true,
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-cx-fda",
        name: "FDA Prescribing Information (NDA 204153)",
        type: "label",
        date: "Jan 2026",
        status: "approved",
        details: "Section 1 & Section 14 Efficacy Trials",
        citationCount: 92,
      },
    ],
    sections: [
      {
        id: "sec-cx1",
        number: 1,
        title: "Clinical Need & Dual Neurotransmitter Modulation",
        category: "clinical",
        content: "Cardioxa selectively inhibits norepinephrine and serotonin reuptake (2:1 ratio) demonstrating significant reductions in Montgomery-Åsberg Depression Rating Scale (MADRS) at 8 weeks.\n\nThe MADRS separation from placebo reached statistical significance from Week 2 and widened through Week 8, with a treatment difference of -4.1 points at the primary endpoint. A change of this size is clinically meaningful in a moderately depressed population, but the section does not support the word rapid without the Week 2 figure attached.\n\nResponse and remission rates were secondary endpoints and were controlled for multiplicity, so both may be quoted. Cognitive and functional outcomes were exploratory and may not be presented as evidence of benefit, however consistent their direction.",
        claimsCount: 14,
        heldOutCount: 0,
        citations: ["FDA PI §1", "Journal of Clinical Psychiatry 2025"],
      },
    ],
  },
  {
    id: "pulmovax",
    brandName: "PulmoVax",
    genericName: "albuterol / budesonide",
    indication: "Fixed-dose dual bronchodilator / ICS combination for asthma maintenance",
    therapyArea: "Respiratory",
    regulatoryAnchor: "FDA",
    gradient: "linear-gradient(145deg,#133b34,#1c6356 50%,#349e8a)",
    accentColor: "#0ea5e9",
    initials: "PV",
    sectionsCount: 21,
    claimsCited: 230,
    claimsHeldOut: 0,
    verifiedClaimsCount: 230,
    totalClaimsCount: 230,
    healthStatus: "healthy",
    sourcesCount: 9,
    lastUpdated: "Curated Sample",
    status: "complete",
    isSample: true,
    documentType: "commercial",
    approvals: approvedByTeam(),
    sources: [
      {
        id: "src-pv-label",
        name: "Global WHO / FDA Monograph & Pivotal MANDALA Phase III",
        type: "label",
        date: "Feb 2026",
        status: "approved",
        details: "Pivotal MANDALA & DENALI clinical readouts",
        citationCount: 138,
      },
    ],
    sections: [
      {
        id: "sec-pv1",
        number: 1,
        title: "Annualized Severe Exacerbation Risk Divergence",
        category: "clinical",
        content: "Fixed combination albuterol/budesonide reduced risk of severe exacerbations by 27% compared with albuterol monotherapy in patients with moderate-to-severe asthma.\n\nExacerbation reduction was the primary endpoint of a 52-week event-driven study in patients with at least one severe exacerbation in the preceding year. The comparator was albuterol alone, not an inhaled corticosteroid maintenance regimen, and any claim must name the comparator or it overstates the position.\n\nRescue use fell by a mean of 0.9 actuations per day and lung function improved on a measure that was secondary and not multiplicity-controlled. The fixed combination is indicated as needed, and no statement may present it as a maintenance therapy.",
        claimsCount: 22,
        heldOutCount: 0,
        citations: ["MANDALA Trial NEJM", "FDA Full USPI"],
      },
    ],
  },
];

export const NEW_DOSSIER_TEMPLATE: BrandDossier = {
  id: "aveloxa",
  brandName: "Aveloxa",
  genericName: "aveloxotide dipropionate",
  indication: "Maintenance therapy for severe eosinophilic asthma in patients aged 12 and older",
  therapyArea: "Respiratory",
  regulatoryAnchor: "FDA",
  gradient: "linear-gradient(145deg,#ff5b2d,#fd4816 50%,#b82f0c)",
  accentColor: "#fd4816",
  initials: "AV",
  sectionsCount: 18,
  claimsCited: 187,
  claimsHeldOut: 3,
  sourcesCount: 1,
  lastUpdated: "Just now",
  status: "complete",
  documentType: "commercial",
  approvals: pendingApprovals(),
  // Only the label ships pre-verified — the rest of the regulatory
  // checklist (clinical trial record, pivotal publication, HEOR,
  // congress deck) starts pending so the Sources step's upload
  // checklist has real work to demonstrate.
  sources: [
    {
      id: "av-label",
      name: "FDA Prescribing Information (Rev. 01/2026)",
      type: "label",
      date: "Jan 2026",
      status: "approved",
      details: "Full US Prescribing Information including Highlights and Section 14",
      citationCount: 94,
    },
  ],
  sections: [
    {
      id: "sec-a1",
      number: 1,
      title: "Executive Summary & Clinical Need",
      category: "commercial",
      content: "Aveloxa (aveloxotide dipropionate) is a precision biologic engineered to selectively inhibit the IL-5Rα pathway, producing rapid and sustained depletion of circulating eosinophils in severe uncontrolled asthma.\n\nEosinophil depletion is measurable within twenty-four hours of the first dose and sustained through the dosing interval, with counts remaining suppressed at trough across 52 weeks. The mechanism is receptor-directed rather than ligand-directed, which is the distinction that supports the word selective and should not be dropped.\n\nThe indication covers severe asthma with an eosinophilic phenotype as add-on maintenance treatment. It is not indicated for the relief of acute bronchospasm or status asthmaticus, and no material may position it as a rescue medicine.",
      claimsCount: 11,
      heldOutCount: 0,
      citations: ["FDA PI Section 1", "AURA-ASTHMA Phase III (NEJM 2025)"],
    },
    {
      id: "sec-a2",
      number: 2,
      title: "Exacerbation Reduction & Lung Function",
      category: "clinical",
      content: "In patients with baseline blood eosinophils ≥ 300 cells/µL, Aveloxa demonstrated a 68% reduction in annualized asthma exacerbation rates (AAER) vs placebo (rate ratio 0.32; 95% CI: 0.25–0.41; p < 0.0001). Pre-bronchodilator FEV1 improved by +240 mL at Week 52.\n\nThe exacerbation result held across both pivotal studies and in the pre-specified subgroups defined by baseline eosinophil count, maintenance corticosteroid use and prior exacerbation history. The effect was smaller below 150 cells per microlitre, and that threshold should be stated whenever a single pooled figure is used.\n\nLung function and quality-of-life endpoints were hierarchically tested and both met significance, so the FEV1 figure and the ACQ-5 improvement may both be quoted. Oral corticosteroid reduction was an endpoint in a separate study and its result may not be attributed to these trials.",
      claimsCount: 26,
      heldOutCount: 1,
      citations: ["AURA-ASTHMA Phase III (NEJM 2025)", "ClinicalTrials.gov NCT05118942"],
    },
    {
      id: "sec-a3",
      number: 3,
      title: "Mechanism of Action & Target Specificity",
      category: "clinical",
      content: "Aveloxa binds domain 1 of the IL-5 receptor alpha chain with high selectivity (Kd = 12 pM), directing antibody-dependent cell-mediated cytotoxicity (ADCC) to eliminate eosinophils and basophils within 24 hours of first administration.\n\nBinding affinity was determined by surface plasmon resonance against the human receptor and confirmed in a cell-based assay; the picomolar figure describes the receptor interaction, not a clinical potency, and the two must not be presented as the same thing.\n\nDepletion is antibody-dependent and therefore requires effector function, which is why the molecule is afucosylated. Basophil depletion accompanies the eosinophil effect and is stated in the label; the clinical consequence of that second effect has not been established and no benefit may be claimed from it.",
      claimsCount: 18,
      heldOutCount: 0,
      citations: ["FDA PI Section 12.1", "Journal of Allergy and Clinical Immunology 2025"],
    },
    {
      id: "sec-a4",
      number: 4,
      title: "Safety, Tolerability & Immunogenicity",
      category: "safety",
      content: "The most common adverse reactions (incidence ≥ 3% and greater than placebo) were nasopharyngitis (6.4% vs 5.8%) and headache (4.2% vs 3.6%). Neutralizing anti-drug antibody incidence was under 1.2% through 52 weeks.\n\nInjection-site reactions occurred in 2.8% versus 1.9% and were mild in all but two cases across the programme. No case of anaphylaxis was reported in the controlled period, though the label carries the class hypersensitivity warning and that warning must accompany any tolerability statement.\n\nAnti-drug antibody formation did not affect exposure, eosinophil depletion or exacerbation rate in the subgroup analysis. Helminth infection was not studied and the label advises treating pre-existing infection before initiation, which is the only permissible statement on that topic.",
      claimsCount: 19,
      heldOutCount: 1,
      citations: ["FDA PI Section 6.1 Adverse Reactions"],
    },
    {
      id: "sec-a5",
      number: 5,
      title: "Dosage, Delivery & Prefilled Pen",
      category: "regulatory",
      content: "Administered as 30 mg subcutaneously once every 4 weeks using a single-dose autoinjector prefilled pen, designed for at-home patient administration following HCP training.\n\nThe autoinjector was evaluated in a human-factors study with 82 untrained participants and a successful-administration rate of 98.8%. Self-administration is permitted after training by a healthcare professional, and material aimed at patients must carry that condition.\n\nThe pen is stored refrigerated and may be held at room temperature for up to fourteen days before use. A missed dose should be given as soon as it is remembered and the four-week schedule resumed from that date.",
      claimsCount: 12,
      heldOutCount: 0,
      citations: ["FDA PI Section 2 Dosage and Administration"],
    },
  ],
};
